Erganiser/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings  # new
from django.conf.urls.static import static  # new

from users import views as user_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("logbook.urls")),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path("register/", user_views.register, name="register"),
    path("profile/", user_views.profile, name="profile"),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_form.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_complete",
    ),
    path("oauth_with_c2", user_views.oauth_with_c2, name="oauth_with_c2"),
    path("verification/", include("verify_email.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

logbook/urls.py
from django.urls import path

from .views import (
    ErgDeleteView,
    ErgDetailView,
    ErgUpdateView,
    Index,
    LogErg,
    LogErgTest,
    MyErgHistory,
    SquadScoreBoard,
    sync_c2_erg_data,
)

app_name = "logbook"

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("log-erg", LogErg.as_view(), name="log-erg"),
    path("log-erg-test", LogErgTest.as_view(), name="log-erg-test"),
    path("erg-history", MyErgHistory.as_view(), name="erg-history"),
    path("erg-detail/<uuid:pk>", ErgDetailView.as_view(), name="erg-detail"),
    # path('erg-scores', SquadErgScores.as_view(), name='erg-scores'),
    path("update-erg/<uuid:pk>", ErgUpdateView.as_view(), name="update-erg"),
    path("delete-erg/<uuid:pk>", ErgDeleteView.as_view(), name="delete-erg"),
    path(
        "squad-scoreboard/<int:year>/<int:month>",
        SquadScoreBoard.as_view(month_format="%m"),
        name="squad-scoreboard",
    ),
    path("sync_c2_erg_data/", sync_c2_erg_data, name="sync_c2_erg_data"),
    path("sync_c2_erg_data/<str:latest>", sync_c2_erg_data, name="sync_c2_erg_data"),
]

logbook/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from users.models import Member


class Erg(models.Model):
    c2_logbook_id = models.CharField(max_length=250, blank=True, null=True, unique=True)
    id = models.UUIDField("ID", primary_key=True, default=uuid.uuid4, editable=False)
    description = models.CharField(max_length=5000, blank=True, null=True)
    distance = models.PositiveIntegerField()
    name = models.CharField(max_length=200, blank=True, null=True)
    effort = models.CharField(
        max_length=8,
        choices=[
            ("low", _("low")),
            ("moderate", _("moderate")),
            ("intense", _("intense")),
        ],
        blank=True,
        null=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    split_time = models.DurationField()
    avg_spm = models.PositiveIntegerField(null=True, blank=True)
    avg_heartrate = models.PositiveIntegerField(null=True, blank=True)
    is_test = models.BooleanField(default=False)

    class Meta:
        abstract = True


# class PlannedErg(Erg):
#     """
#     2nd stage: Plan ergs, which needs to be done
#     """
#     est_time = models.DurationField(null=True, blank=True)
#     aimed_date = models.DateField(null=True, blank=True)
#     planned_for = models.ForeignKey(Squad, on_delete=models.CASCADE,
#     blank=True,
#                                     null=True)
#     created_by = models.ForeignKey(Member, related_name="creator",
#                                    on_delete=models.CASCADE, null=True)
#
#     def __str__(self):
#         return "Planned Erg %s" % self.name
#
#     # def get_absolute_url(self):
#     #     return reverse('logbook:planned_erg_detail',
#     #                    kwargs={'pk': self.pk})


class FinishedErg(Erg):
    """
    log your finished erg in here
    """

    completed_at = models.DateField()
    result_time = models.DurationField(null=True)
    completed_by = models.ForeignKey(
        Member, on_delete=models.CASCADE, null=True
    )  # This should never be null

    # planned_erg = models.ForeignKey(to=PlannedErg,
    #                                 on_delete=models.CASCADE, blank=True,
    #                                 null=True)

    def __str__(self):
        return "Completed Erg %s" % self.name

    def get_absolute_url(self):
        return reverse("logbook:erg-detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = f"{self.distance}m. Row"
        super().save(*args, **kwargs)


# class PlannedWorkout(models.Model):
#     """
#     2nd stage: You can plan multiple ergs for one workout
#     """
#     created_at = models.DateTimeField(auto_now_add=True)
#     id = models.UUIDField('ID', primary_key=True,
#                           default=uuid.uuid4, editable=False)
#     planned_erg = models.ForeignKey(PlannedErg, null=True, blank=True,
#                                     on_delete=models.CASCADE)
#
#
# class FinishedWorkout(models.Model):
#     """
#     Log multiple ergs in one workout
#     """
#     id = models.UUIDField('ID', primary_key=True,
#                           default=uuid.uuid4, editable=False)
#     finished_erg = models.ForeignKey(FinishedErg, null=True, blank=True,
#                                      on_delete=models.CASCADE)
#     planned_workout = models.ForeignKey(PlannedWorkout, null=True,
#                                         blank=True, on_delete=models.CASCADE)
#     completed_at = models.DateTimeField(null=True, blank=True)
#     completed_by = models.ForeignKey(Member, on_delete=models.CASCADE,
#                                      null=True)

logbook/views.py
import calendar
import json
import random
from datetime import timedelta

import requests
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.datetime_safe import datetime
from django.utils.timezone import now
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
)
from django.views.generic.dates import MonthArchiveView

from logbook.forms import LogErgForm, LogErgTestForm, UpdateErgForm
from users.models import Squad
from .models import FinishedErg


class Index(TemplateView):
    def get_template_names(self):
        if self.request.user.is_authenticated:
            template_name = "logbook/index.html"
        else:
            template_name = "logbook/login_required.html"
        return template_name

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        splits_to_display = []
        # squads_erg_tests = FinishedErg.objects.filter(is_test=True)
        if self.request.user.is_authenticated:
            # Get data for Recent Ergs
            my_last_ergs = FinishedErg.objects.filter(
                completed_by=self.request.user.member
            ).order_by("-completed_at")[:3]
            my_last_tests = FinishedErg.objects.filter(
                completed_by=self.request.user.member, is_test=True
            ).order_by("-completed_at")[:3]

            if self.request.user.member.is_coach:
                # Squad selection given from the template
                squad = self.request.GET.get("squad")
                if not squad:
                    # If no squad_id is selected just use s random one
                    squad_obj = random.choice(get_list_of_squads())
                    squad = squad_obj.id
                    context["current_squad"] = squad_obj
                else:
                    context["current_squad"] = Squad.objects.get(id=squad)
                erg_dist_of_month = get_erg_dist_of_month(squad)
                best_end_split_tests = get_best_erg_test_of_squad(
                    erg_dist_of_month, squad
                )
                top_three_splits = best_end_split_tests[:3]
                splits_to_display = top_three_splits

            else:
                # Identify which distance is given as test metrics for the
                # month
                if self.request.user.member.squad:
                    erg_dist_of_month = get_erg_dist_of_month(
                        self.request.user.member.squad.id
                    )
                    squad = self.request.user.member.squad.squad_name
                    # Get the three best erg scores for that distance in that
                    # month from the squad of the logged in user
                    best_end_split_tests = get_best_erg_test_of_squad(
                        erg_dist_of_month, self.request.user.member.squad.id
                    )
                    users_best_split = (
                        FinishedErg.objects.filter(
                            completed_by=self.request.user.member,
                            is_test=True,
                            completed_at__month=now().month,
                            distance=erg_dist_of_month,
                        )
                        .order_by("split_time")
                        .first()
                    )
                    top_three_splits = best_end_split_tests[:3]
                else:
                    users_best_split = None
                    erg_dist_of_month = None

                # Get the best split for that distance and month from the
                # currently logged in user to then see if he is in the top 3
                # Check if user is in top3, if so then just display the top3
                # and highlight him in it, if not display his position under
                # the top3 and highlight it in red

                if not users_best_split:
                    # USER has not entered an erg test
                    users_position = None

                elif users_best_split in top_three_splits:
                    # USERS test split is in the top 3 splits of the squad
                    splits_to_display = top_three_splits
                    users_position = list(splits_to_display).index(users_best_split) + 1

                else:
                    # USERS tests split is not in the top 3 splits of the squad
                    splits_to_display += top_three_splits
                    splits_to_display.append(users_best_split)
                    # Get position of users split in leaderboard
                    users_position = (
                        list(best_end_split_tests).index(users_best_split) + 1
                    )
                context["users_best_split"] = users_best_split
                context["users_position"] = users_position
                context["quote"] = get_rndm_motiv_quote(users_position)
                # context['current_squad'] = squad

            q = self.request.GET.get("isTest")
            if q == "True":
                my_last_ergs = my_last_tests

            context["my_last_ergs"] = my_last_ergs
            context["squads"] = get_list_of_squads()
            context["erg_dist_of_month"] = erg_dist_of_month
            context["current_month"] = now().month
            context["current_month_char"] = calendar.month_abbr[now().month]
            context["current_year"] = now().year
            context["splits_to_display"] = splits_to_display
            context["q"] = q
        return context


def get_rndm_motiv_quote(users_position):
    """
    This function returns a winning related quote, if the user is at the first
    place in his squad, otherwise it returns a random motivational quote.
    """
    with open("Erganiser/static/assets/data/quotes.json") as json_file:
        data = json.load(json_file)
        if users_position == "1":
            quotes = data["winner_quotes"]
        else:
            quotes = data["motivational_quotes"]
        quote = random.choice(quotes)
        return quote


def get_list_of_squads():
    squads = Squad.objects.all()
    return squads


def get_erg_dist_of_month(squad_id):
    """
    This function returns the distance of the erg test of the month for a given
    squad.
    """
    ergs_of_the_month = FinishedErg.objects.filter(
        completed_at__month=now().month, is_test=True, completed_by__squad__id=squad_id
    )
    if not ergs_of_the_month:
        return None
    this_month_dist = (
        ergs_of_the_month.values_list("distance", flat=True)
        .distinct()
        .order_by("-distance")
    )
    erg_endurance_dist = this_month_dist.first()
    return erg_endurance_dist


def get_best_erg_test_of_squad(dist_of_month, squad_id):
    """
    This orders the erg tests of the month by the split time to order the
    fastest erg tests first.
    """
    best_ergs = FinishedErg.objects.filter(
        completed_at__month=now().month,
        is_test=True,
        completed_by__squad__id=squad_id,
        distance=dist_of_month,
    ).order_by("split_time")
    return best_ergs


def convert_date_field(date):
    """
    This function converts a date string into a django datefield object.
    """
    date_object = datetime.strptime(date, "%Y-%m-%d %H:%M:%S")
    django_datefield = date_object.date()
    return django_datefield


def calculate_split_time(total_time, distance):
    """
    This function calculates the split time for a given distance and total time.
    """
    split_in_sec = 500 * ((total_time * 0.1) / distance)
    split = timedelta(seconds=round(split_in_sec))
    return split


def format_duration(time):
    """
    This function formats the duration of a workout into a timedelta object.
    """
    formatted_time = timedelta(seconds=round(time * 0.1))
    return formatted_time


def create_erg_object(workout, request):
    """
    This function creates an erg object in the database. It is used to store
    the results of an api call to get workouts done on a concept2 erg.
    https://log.concept2.com/developers/documentation/#logbook-users-results
    """
    try:
        erg = FinishedErg.objects.create(
            name="Concept2 {distance}m. Row".format(distance=workout["distance"]),
            c2_logbook_id=workout["id"],
            completed_by=request.user.member,
            distance=workout["distance"],
            avg_spm=workout["stroke_rate"] if "stroke_rate" in workout else None,
            completed_at=convert_date_field(workout["date"]),
            result_time=format_duration(workout["time"]),
            split_time=calculate_split_time(workout["time"], workout["distance"]),
            avg_heartrate=workout["heart_rate"]["average"]
            if "heart_rate" in workout and "average" in workout["heart_rate"]
            else None,
        )
        erg.save()
    except IntegrityError as e:
        if "logbook_finishederg_c2_logbook_id_key" in e.args[0]:
            messages.add_message(request, messages.INFO, "Already synced this Erg")
            return messages
    return erg


def get_results_api_call_url(user_profile, has_latest):
    """
    This function returns the url for the api call to get either all the
    workouts of a user or only the latest ones, which is determined by the
    has_latest parameter. The last_sync param in the user profile is used to
    determine the date from which the latest workouts should be synced.
    """
    url = (
        "https://log.concept2.com/api/users/{"
        "c2_logbook_id}/results?type=rower".format(
            c2_logbook_id=user_profile.c2_logbook_id
        )
    )

logbook/templates/logbook/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Web Application to display organise your
rowing
squads workouts">

    <!-- Bootstrap CSS -->

    <script src="https://kit.fontawesome.com/41ed01ee58.js"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">


    <link rel="stylesheet" href="{% static 'logbook/main.css' %}"
          id="main-style-link"/>
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}"
          id="main-style-link"/>

    {% if title %}
        <title>Erganiser- {{ title }}</title>
    {% else %}
        <title>Erganiser</title>
    {% endif %}
    {{ form.media }}
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Erganiser</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page"
                       href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page"
                       href="/log-erg">Log Erg</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page"
                       href="/erg-history">My History</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page"
                       href="
{% url 'logbook:squad-scoreboard' year=current_year month=current_month %}">Leaderboard</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<main class="container">
    {% if messages %}
        <div class="alert alert-warning alert-dismissible fade show"
             role="alert">
            <ul class="messages">
                {% for message in messages %}
                    {% if "export_records" or "download_file" in message.tags %}
                        <li  {% if message.tags %}
                            class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
                    {% endif %}
                {% endfor %}
            </ul>
            <button type="button" class="close" data-dismiss="alert"
                    aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    {% block content %}
    {% endblock %}
</main>
{% include 'logbook/partials/_footer.html' %}
</body>
</html>

logbook/templates/logbook/erg_history.html
{% extends "logbook/base.html" %}

{% block content %}
    <div class="container">
        <h3 class="mt-3">Recent Ergs </h3>
        <div class="erg-history-header">
            <div class="row">
                <div class="col-4">
                    <p>Date</p>
                </div>
                <div class="col-4">
                    <p>Duration</p>
                </div>
                <div class="col-4">
                    <p>Distance</p>
                </div>
            </div>
        </div>
        {% for erg in page_obj %}
            <a href="{% url 'logbook:erg-detail' erg.pk %}">
                <div class="erg-preview card mt-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-4">
                                <div class="erg-attr">
                                    <p>{{ erg.completed_at|date:"d.m.y" }}</p>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="erg-attr">
                                    <p>{{ erg.result_time }}</p>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="erg-attr">
                                    <p>{{ erg.distance }}m <i
                                            class="fa-solid fa-chevron-right"></i>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            {#                <li>#}
            {#                    <a href="{% url 'logbook:erg-detail' erg.pk %}">{{ erg.name }}#}
            {#                        - {{ erg.completed_by }}#}
            {#                        - {{ erg.completed_at.date }}</a> <a#}
            {#                        href="{% url 'logbook:update-erg' erg.pk %}">Update</a>#}
            {#                    <a#}
            {#                            href="{% url 'logbook:delete-erg' erg.pk %}">x</a>#}
            {#                </li>#}
        {% empty %}
            <div class="text-center font-weight-bold mt-3">
                <p>Your Logbook appears to be empty!</p>
                <a class="btn btn-primary"
                   href="{% url 'logbook:log-erg' %}">Make your
                    first Logbook Entry!
                </a>
            </div>
        {% endfor %}
        <div class="pagination justify-content-center mt-3">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a class="secondary" href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">Prev.</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="secondary"
               href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
        </div>
    </div>


{% endblock %}

logbook/templates/logbook/finished_erg_detail.html
{% extends "logbook/base.html" %}

{% block content %}
    <div class="erg-detail card mt-3">
        <p class="date text-right mt-3 mr-3">
            {{ object.completed_at|date:"d.m.Y" }}</p>
        <h3 class="ml-3">{{ object.name }}</h3>
        <hr class="underline">
        <div class="card-body">
            {% if object.is_test == True %}
                <p>This your metrics entry for
                    {{ object.completed_at|date:"F" }}</p>
            {% endif %}
            <div class="row">
                <div class="col-6"><p>Time</p></div>
                <div class="col-6"><p>{{ object.result_time }}</p></div>
                <div class="col-6"><p>Distance</p></div>
                <div class="col-6"><p>{{ object.distance }}</p></div>
                <div class="col-6"><p>Split</p></div>
                <div class="col-6"><p>{{ object.split_time }}</p></div>
            </div>
            <a class="btn btn-primary" href=
                    "{% url 'logbook:update-erg' pk=object.id %}">Edit Erg</a>
            <a class="btn btn-danger delete-button" href=
                    "{% url 'logbook:delete-erg' pk=object.id %}">Delete Erg</a>

        </div>
    </div>
    </div>
    </div>

{% endblock %}

logbook/templates/logbook/index.html
{% extends "logbook/base.html" %}
{% load static %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-4">
                <div class="add-erg card my-3 mt-5">
                    <a class="log-erg" href="{% url 'logbook:log-erg' %}">
                        <div class="card-body">
                            <div class="row d-flex align-items-center index">
                                <div class="col-2 justify-content-center">
                                    <i class="fa-solid fa-plus fa-3x"></i>
                                </div>
                                <div class="col-10 justify-content-center mt-2">
                                    <h2 class="index-page">
                                        Log New Erg</h2></div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-12 col-4">
                <div class="card my-3 card bg-primary-dark dashnnum-card dashnum-card-small overflow-hidden my-3">
                    {#                    <a href="{% url 'logbook:erg-history' %}">#}
                    <div class="card-body">
                        <div class="row align-items-center">
                            <div class="col mt-2">
                                <h2>Recent Ergs</h2>
                            </div>
                            <div class="col-auto">
                                <ul class="nav nav-pills justify-content-end mb-0">
                                    <li class="nav-item">
                                        <form method="get">
                                            {% csrf_token %}
                                            {% if q != "False" %}
                                                <button class="nav-link text-white active"
                                                        type="submit"
                                                        name="isTest"
                                                        value="False">All
                                                </button>
                                            {% else %}
                                                <button class="nav-link
                                                text-white inactive"
                                                        type="submit"
                                                        name="isTest"
                                                        value="False">All
                                                </button>
                                            {% endif %}
                                        </form>
                                    </li>
                                    <li class="nav-item">
                                        <form method="get">
                                            {% csrf_token %}
                                            {% if q != "True" %}
                                                <button class="nav-link text-white active"
                                                        type="submit"
                                                        name="isTest"
                                                        value="True">Test
                                                </button>
                                            {% else %}
                                                <button class="nav-link
                                                text-white inactive"
                                                        type="submit"
                                                        name="isTest"
                                                        value="True">Test
                                                </button>
                                            {% endif %}
                                        </form>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        {% if my_last_ergs %}
                            {% include "logbook/partials/_erg_history.html" with  ergs=my_last_ergs %}
                        {% else %}
                            <div class="text-center font-weight-bold mt-3">
                                <p>Your Logbook appears to be empty!</p>
                            </div>
                        {% endif %}
                    </div>
                    <div class="text-center">
                        {% if my_last_ergs %}
                            <a class="btn btn-primary"
                               href="{% url 'logbook:erg-history' %}">Show More
                                ...</a>
                        {% else %}
                            <a class="btn btn-primary"
                               href="{% url 'logbook:log-erg' %}">Make your
                                first Logbook Entry!
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-12 col-4">
                <div class="card my-3">
                    {% if user.member.is_coach %}
                        {% include "logbook/partials/_leaderboard_coach.html" %}
                    {% else %}
                        {% include "logbook/partials/_leaderboard_member.html" %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>


    {#    <a href="{% url 'logbook:squad-scoreboard' current_year current_month %}">#}



{% endblock %}