Erganiser/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.conf import settings  # new
from django.conf.urls.static import static  # new

from users import views as user_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("logbook.urls")),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path("register/", user_views.register, name="register"),
    path("profile/", user_views.profile, name="profile"),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_form.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_complete",
    ),
    path("oauth_with_c2", user_views.oauth_with_c2, name="oauth_with_c2"),
    path("verification/", include("verify_email.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

logbook/urls.py
from django.urls import path

from .views import (
    ErgDeleteView,
    ErgDetailView,
    ErgUpdateView,
    Index,
    LogErg,
    LogErgTest,
    MyErgHistory,
    SquadScoreBoard,
    sync_c2_erg_data,
)

app_name = "logbook"

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("log-erg", LogErg.as_view(), name="log-erg"),
    path("log-erg-test", LogErgTest.as_view(), name="log-erg-test"),
    path("erg-history", MyErgHistory.as_view(), name="erg-history"),
    path("erg-detail/<uuid:pk>", ErgDetailView.as_view(), name="erg-detail"),
    # path('erg-scores', SquadErgScores.as_view(), name='erg-scores'),
    path("update-erg/<uuid:pk>", ErgUpdateView.as_view(), name="update-erg"),
    path("delete-erg/<uuid:pk>", ErgDeleteView.as_view(), name="delete-erg"),
    path(
        "squad-scoreboard/<int:year>/<int:month>",
        SquadScoreBoard.as_view(month_format="%m"),
        name="squad-scoreboard",
    ),
    path("sync_c2_erg_data/", sync_c2_erg_data, name="sync_c2_erg_data"),
    path("sync_c2_erg_data/<str:latest>", sync_c2_erg_data, name="sync_c2_erg_data"),
]

logbook/models.py
import uuid

from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from users.models import Member


class Erg(models.Model):
    c2_logbook_id = models.CharField(max_length=250, blank=True, null=True, unique=True)
    id = models.UUIDField("ID", primary_key=True, default=uuid.uuid4, editable=False)
    description = models.CharField(max_length=5000, blank=True, null=True)
    distance = models.PositiveIntegerField()
    name = models.CharField(max_length=200, blank=True, null=True)
    effort = models.CharField(
        max_length=8,
        choices=[
            ("low", _("low")),
            ("moderate", _("moderate")),
            ("intense", _("intense")),
        ],
        blank=True,
        null=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    split_time = models.DurationField()
    avg_spm = models.PositiveIntegerField(null=True, blank=True)
    avg_heartrate = models.PositiveIntegerField(null=True, blank=True)
    is_test = models.BooleanField(default=False)

    class Meta:
        abstract = True


# class PlannedErg(Erg):
#     """
#     2nd stage: Plan ergs, which needs to be done
#     """
#     est_time = models.DurationField(null=True, blank=True)
#     aimed_date = models.DateField(null=True, blank=True)
#     planned_for = models.ForeignKey(Squad, on_delete=models.CASCADE,
#     blank=True,
#                                     null=True)
#     created_by = models.ForeignKey(Member, related_name="creator",
#                                    on_delete=models.CASCADE, null=True)
#
#     def __str__(self):
#         return "Planned Erg %s" % self.name
#
#     # def get_absolute_url(self):
#     #     return reverse('logbook:planned_erg_detail',
#     #                    kwargs={'pk': self.pk})


class FinishedErg(Erg):
    """
    log your finished erg in here
    """

    completed_at = models.DateField()
    result_time = models.DurationField(null=True)
    completed_by = models.ForeignKey(
        Member, on_delete=models.CASCADE, null=True
    )  # This should never be null

    # planned_erg = models.ForeignKey(to=PlannedErg,
    #                                 on_delete=models.CASCADE, blank=True,
    #                                 null=True)

    def __str__(self):
        return "Completed Erg %s" % self.name

    def get_absolute_url(self):
        return reverse("logbook:erg-detail", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = f"{self.distance}m. Row"
        super().save(*args, **kwargs)


# class PlannedWorkout(models.Model):
#     """
#     2nd stage: You can plan multiple ergs for one workout
#     """
#     created_at = models.DateTimeField(auto_now_add=True)
#     id = models.UUIDField('ID', primary_key=True,
#                           default=uuid.uuid4, editable=False)
#     planned_erg = models.ForeignKey(PlannedErg, null=True, blank=True,
#                                     on_delete=models.CASCADE)
#
#
# class FinishedWorkout(models.Model):
#     """
#     Log multiple ergs in one workout
#     """
#     id = models.UUIDField('ID', primary_key=True,
#                           default=uuid.uuid4, editable=False)
#     finished_erg = models.ForeignKey(FinishedErg, null=True, blank=True,
#                                      on_delete=models.CASCADE)
#     planned_workout = models.ForeignKey(PlannedWorkout, null=True,
#                                         blank=True, on_delete=models.CASCADE)
#     completed_at = models.DateTimeField(null=True, blank=True)
#     completed_by = models.ForeignKey(Member, on_delete=models.CASCADE,
#                                      null=True)

logbook/views.py
import calendar
import json
import random
from datetime import timedelta

import requests
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.datetime_safe import datetime
from django.utils.timezone import now
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    TemplateView,
    UpdateView,
)
from django.views.generic.dates import MonthArchiveView

from logbook.forms import LogErgForm, LogErgTestForm, UpdateErgForm
from users.models import Squad
from .models import FinishedErg


class Index(TemplateView):
    def get_template_names(self):
        if self.request.user.is_authenticated:
            template_name = "logbook/index.html"
        else:
            template_name = "logbook/login_required.html"
        return template_name

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        splits_to_display = []
        # squads_erg_tests = FinishedErg.objects.filter(is_test=True)
        if self.request.user.is_authenticated:
            # Get data for Recent Ergs
            my_last_ergs = FinishedErg.objects.filter(
                completed_by=self.request.user.member
            ).order_by("-completed_at")[:3]
            my_last_tests = FinishedErg.objects.filter(
                completed_by=self.request.user.member, is_test=True
            ).order_by("-completed_at")[:3]

            if self.request.user.member.is_coach:
                # Squad selection given from the template
                squad = self.request.GET.get("squad")
                if not squad:
                    # If no squad_id is selected just use s random one
                    squad_obj = random.choice(get_list_of_squads())
                    squad = squad_obj.id
                    context["current_squad"] = squad_obj
                else:
                    context["current_squad"] = Squad.objects.get(id=squad)
                erg_dist_of_month = get_erg_dist_of_month(squad)
                best_end_split_tests = get_best_erg_test_of_squad(
                    erg_dist_of_month, squad
                )
                top_three_splits = best_end_split_tests[:3]
                splits_to_display = top_three_splits

            else:
                # Identify which distance is given as test metrics for the
                # month
                if self.request.user.member.squad:
                    erg_dist_of_month = get_erg_dist_of_month(
                        self.request.user.member.squad.id
                    )
                    squad = self.request.user.member.squad.squad_name
                    # Get the three best erg scores for that distance in that
                    # month from the squad of the logged in user
                    best_end_split_tests = get_best_erg_test_of_squad(
                        erg_dist_of_month, self.request.user.member.squad.id
                    )
                    users_best_split = (
                        FinishedErg.objects.filter(
                            completed_by=self.request.user.member,
                            is_test=True,
                            completed_at__month=now().month,
                            distance=erg_dist_of_month,
                        )
                        .order_by("split_time")
                        .first()
                    )
                    top_three_splits = best_end_split_tests[:3]
                else:
                    users_best_split = None
                    erg_dist_of_month = None

                # Get the best split for that distance and month from the
                # currently logged in user to then see if he is in the top 3
                # Check if user is in top3, if so then just display the top3
                # and highlight him in it, if not display his position under
                # the top3 and highlight it in red

                if not users_best_split:
                    # USER has not entered an erg test
                    users_position = None

                elif users_best_split in top_three_splits:
                    # USERS test split is in the top 3 splits of the squad
                    splits_to_display = top_three_splits
                    users_position = list(splits_to_display).index(users_best_split) + 1

                else:
                    # USERS tests split is not in the top 3 splits of the squad
                    splits_to_display += top_three_splits
                    splits_to_display.append(users_best_split)
                    # Get position of users split in leaderboard
                    users_position = (
                        list(best_end_split_tests).index(users_best_split) + 1
                    )
                context["users_best_split"] = users_best_split
                context["users_position"] = users_position
                context["quote"] = get_rndm_motiv_quote(users_position)
                # context['current_squad'] = squad

            q = self.request.GET.get("isTest")
            if q == "True":
                my_last_ergs = my_last_tests

            context["my_last_ergs"] = my_last_ergs
            context["squads"] = get_list_of_squads()
            context["erg_dist_of_month"] = erg_dist_of_month
            context["current_month"] = now().month
            context["current_month_char"] = calendar.month_abbr[now().month]
            context["current_year"] = now().year
            context["splits_to_display"] = splits_to_display
            context["q"] = q
        return context


def get_rndm_motiv_quote(users_position):
    """
    This function returns a winning related quote, if the user is at the first
    place in his squad, otherwise it returns a random motivational quote.
    """
    with open("Erganiser/static/assets/data/quotes.json") as json_file:
        data = json.load(json_file)
        if users_position == "1":
            quotes = data["winner_quotes"]
        else:
            quotes = data["motivational_quotes"]
        quote = random.choice(quotes)
        return quote


def get_list_of_squads():
    squads = Squad.objects.all()
    return squads


def get_erg_dist_of_month(squad_id):
    """
    This function returns the distance of the erg test of the month for a given
    squad.
    """
    ergs_of_the_month = FinishedErg.objects.filter(
        completed_at__month=now().month, is_test=True, completed_by__squad__id=squad_id
    )
    if not ergs_of_the_month:
        return None
    this_month_dist = (
        ergs_of_the_month.values_list("distance", flat=True)
        .distinct()
        .order_by("-distance")
    )
    erg_endurance_dist = this_month_dist.first()
    return erg_endurance_dist


def get_best_erg_test_of_squad(dist_of_month, squad_id):
    """
    This orders the erg tests of the month by the split time to order the
    fastest erg tests first.
    """
    best_ergs = FinishedErg.objects.filter(
        completed_at__month=now().month,
        is_test=True,
        completed_by__squad__id=squad_id,
        distance=dist_of_month,
    ).order_by("split_time")
    return best_ergs


def convert_date_field(date):
    """
    This function converts a date string into a django datefield object.
    """
    date_object = datetime.strptime(date, "%Y-%m-%d %H:%M:%S")
    django_datefield = date_object.date()
    return django_datefield


def calculate_split_time(total_time, distance):
    """
    This function calculates the split time for a given distance and total time.
    """
    split_in_sec = 500 * ((total_time * 0.1) / distance)
    split = timedelta(seconds=round(split_in_sec))
    return split


def format_duration(time):
    """
    This function formats the duration of a workout into a timedelta object.
    """
    formatted_time = timedelta(seconds=round(time * 0.1))
    return formatted_time


def create_erg_object(workout, request):
    """
    This function creates an erg object in the database. It is used to store
    the results of an api call to get workouts done on a concept2 erg.
    https://log.concept2.com/developers/documentation/#logbook-users-results
    """
    try:
        erg = FinishedErg.objects.create(
            name="Concept2 {distance}m. Row".format(distance=workout["distance"]),
            c2_logbook_id=workout["id"],
            completed_by=request.user.member,
            distance=workout["distance"],
            avg_spm=workout["stroke_rate"] if "stroke_rate" in workout else None,
            completed_at=convert_date_field(workout["date"]),
            result_time=format_duration(workout["time"]),
            split_time=calculate_split_time(workout["time"], workout["distance"]),
            avg_heartrate=workout["heart_rate"]["average"]
            if "heart_rate" in workout and "average" in workout["heart_rate"]
            else None,
        )
        erg.save()
    except IntegrityError as e:
        if "logbook_finishederg_c2_logbook_id_key" in e.args[0]:
            messages.add_message(request, messages.INFO, "Already synced this Erg")
            return messages
    return erg


def get_results_api_call_url(user_profile, has_latest):
    """
    This function returns the url for the api call to get either all the
    workouts of a user or only the latest ones, which is determined by the
    has_latest parameter. The last_sync param in the user profile is used to
    determine the date from which the latest workouts should be synced.
    """
    url = (
        "https://log.concept2.com/api/users/{"
        "c2_logbook_id}/results?type=rower".format(
            c2_logbook_id=user_profile.c2_logbook_id
        )
    )

logbook/templates/logbook/partials/_erg_history.html
<div class="container">
    <h1>{{ heading }}</h1>
    <div class="erg-history-header">
        <div class="row">
            <div class="col-4">
                <p>Date</p>
            </div>
            <div class="col-4">
                <p>Duration</p>
            </div>
            <div class="col-4">
                <p>Distance</p>
            </div>
        </div>
    </div>
    {% for erg in ergs %}
        <a href="{% url 'logbook:erg-detail' erg.pk %}">
            <div class="erg-preview card mt-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-4">
                            <div class="erg-attr">
                                <p>{{ erg.completed_at|date:"d.m.y" }}</p>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="erg-attr">
                                <p>{{ erg.result_time }}</p>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="erg-attr">
                                <p>{{ erg.distance }}m <i
                                        class="fa-solid fa-chevron-right"></i>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </a>
        {#                <li>#}
        {#                    <a href="{% url 'logbook:erg-detail' erg.pk %}">{{ erg.name }}#}
        {#                        - {{ erg.completed_by }}#}
        {#                        - {{ erg.completed_at.date }}</a> <a#}
        {#                        href="{% url 'logbook:update-erg' erg.pk %}">Update</a>#}
        {#                    <a#}
        {#                            href="{% url 'logbook:delete-erg' erg.pk %}">x</a>#}
        {#                </li>#}
    {% empty %}
        <li>No ergs yet.</li>
    {% endfor %}
</div>

logbook/templates/logbook/partials/_footer.html
<footer class="py-1 mt-4 base-footer expand-lg">
    <ul class="nav justify-content-center border-bottom pb-1 mb-1">
        <li class="nav-item">
            <a href="https://www.buymeacoffee.com/sebastianlange"
               class="nav-link px-2">Buy me a Coffee</a>
        </li>
        <li class="nav-item"><a href="mailto: bastilange@t-online.de"
                                class="nav-link px-2 ">Contact me</a>
        </li>
        <li class="nav-item"><a
                href="https://ourcs.co.uk/information/flags/isis/"
                class="nav-link px-2 ">Flag Status</a>
        </li>
    </ul>
    <p class="text-center text-muted">© Power-10Coding</p>
</footer>

logbook/templates/logbook/partials/_leaderboard_coach.html
{% load static %}

<div class="card-body leaderboard">
    <div class="row align-items-center">
        <div class="col mt-2">
            <h2>{{ current_squad.squad_name }} Leaderboard </h2>
        </div>
        <div class="col-auto">
            <ul class="nav nav-pills justify-content-end mb-0">
                {% for squad in squads %}
                    <li class="nav-item">
                        <form method="get">
                            {% csrf_token %}
                            <button class="nav-link text-white active"
                                    type="submit"
                                    name="squad"
                                    value="{{ squad.id }}">{{ squad.squad_name }}
                            </button>
                        </form>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% if erg_dist_of_month and splits_to_display %}
        <div class="dist_of_month mt-5 text-center font-weight-bold">
            <p>Best {{ erg_dist_of_month }}m. Splits</p>
        </div>
        <div class="leaderboard-positions mt-5">
            <div class="row">
                <div class="col-4">
                    <div class="placement">
                        <img src="{% static "assets/img/silver.svg" %}"
                             alt="Victory Wreath in Silver"
                             class="img-fluid"/>
                        <p class="text-center mt-1">{{ splits_to_display.1.completed_by }}</p>

                    </div>
                </div>
                <div class="col-4">
                    <div class="placement">
                        <img src="{% static "assets/img/gold.svg" %}"
                             alt="Victory Wreath in Gold"
                             class="img-fluid"/>
                        <p class="text-center mt-1">{{ splits_to_display.0.completed_by }}</p>

                    </div>
                </div>
                <div class="col-4">
                    <div class="placement">
                        <img src="{% static "assets/img/bronze.svg" %}"
                             alt="Victory Wreath in Bronze"
                             class="img-fluid"/>
                        <p class="text-center mt-1">{{ splits_to_display.2.completed_by }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="leaderboard-previews">
            <div class="row">
                <div class="col-12">
                    <a href="{% url 'logbook:squad-scoreboard' current_year current_month %}">
                        <table class="table my-3 pl-1 pr-1">
                            <thead>
                            <tr>
                                <th scope="col">Pos.</th>
                                <th scope="col">Athlete</th>
                                <th scope="col">Time</th>
                                <th scope="col">Split</th>
                            </tr>
                            </thead>
                            <tbody class="leaderboard-previews-body">
                            {% for erg in splits_to_display|slice:":3" %}
                                <tr class="table-row">
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ erg.completed_by }}</td>
                                    <td>{{ erg.result_time }}</td>
                                    <td>{{ erg.split_time }}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </a>
                </div>
            </div>
        </div>
    {% else %}
        <div class="text-center font-weight-bold mt-3 mb-3">
            <p>Oh, this looks so empty here!</p>
            <p>Encourage your athletes to do their metrics!</p>
        </div>
    {% endif %}

</div>

logbook/templates/logbook/partials/_leaderboard_member.html
{% load static %}

{% if not splits_to_display %}
    <div class="card-body leaderboard deactivated">
        <div class="row align-items-center">
            <div class="col mt-2">
                <h2>{{ current_squad }} Leaderboard</h2>
            </div>
        </div>
        <div class="text-center font-weight-bold mt-3 mb-3">
            <p>Oh, this looks so empty here!</p>
        </div>
        <div class="text-center">
            <a class="btn btn-primary"
               href="{% url 'logbook:log-erg-test' %}">
                Be the First
                to log
                your
                Erg Metrics!
            </a>
        </div>
    </div>
{% else %}
    <div class="card-body leaderboard">
        <div class="row align-items-center">
            <div class="col mt-2">
                <h2>{{ current_squad }} Leaderboard</h2>
            </div>
            <div class="col-auto mt-2">
                <p>Dist for {{ current_month_char }}:
                    <br/> {{ erg_dist_of_month }}
                    m.</p>
            </div>
        </div>
        <div class="leaderboard-positions mt-3">
            <div class="row">
                <div class="col-4">
                    <div class="placement">
                        <img src="{% static "assets/img/silver.svg" %}"
                             alt="Victory Wreath in Silver"
                             class="img-fluid"/>
                        <p class="text-center mt-1">{{ splits_to_display.1.split_time }}</p>

                    </div>
                </div>
                <div class="col-4">
                    <div class="placement">
                        <img src="{% static "assets/img/gold.svg" %}"
                             alt="Victory Wreath in Gold"
                             class="img-fluid"/>
                        <p class="text-center mt-1">{{ splits_to_display.0.split_time }}</p>

                    </div>
                </div>
                <div class="col-4">
                    <div class="placement">
                        <img src="{% static "assets/img/bronze.svg" %}"
                             alt="Victory Wreath in Bronze"
                             class="img-fluid"/>
                        <p class="text-center mt-1">{{ splits_to_display.2.split_time }}</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="current-user-position">
            <div class="row">
                <div class="col-12 text-center">
                    <hr class="mx-auto w-50">
                    <h2>Your current Position:</h2>
                    <h2 class="font-weight-bold">{{ users_position }}</h2>
                    <hr class="mx-auto w-50">
                    <div class="quote">
                        {% include "logbook/partials/_quote.html" %}
                    </div>
                </div>
            </div>
        </div>
        <div class="leaderboard-previews">
            <div class="row">
                <div class="col-12">
                    <a href="{% url 'logbook:squad-scoreboard' current_year current_month %}">
                        <table class="table my-3 pl-1 pr-1">
                            <thead>
                            <tr>
                                <th scope="col">Pos.</th>
                                <th scope="col">Dist</th>
                                <th scope="col">Time</th>
                                <th scope="col">Split</th>
                            </tr>
                            </thead>
                            <tbody class="leaderboard-previews-body">
                            {% if splits_to_display|length > 3 %}
                                {% for erg in splits_to_display|slice:":3" %}
                                    <tr class="table-row">
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ erg.distance }}</td>
                                        <td>{{ erg.result_time }}</td>
                                        <td>{{ erg.split_time }}</td>
                                    </tr>
                                {% endfor %}
                            {% else %}
                                {% for erg in splits_to_display %}
                                    {% if erg == users_best_split %}
                                        <tr class="table-row">
                                            {% else %}
                                        <tr class="table-row">
                                    {% endif %}
                                <td>{{ forloop.counter }}</td>
                                <td>{{ erg.distance }}</td>
                                <td>{{ erg.result_time }}</td>
                                <td>{{ erg.split_time }}</td>
                                </tr>
                                {% endfor %}
                            {% endif %}
                            </tbody>
                        </table>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endif %}

logbook/templates/logbook/partials/_quote.html
<blockquote class="blockquote">
    <p class="font-weight-light text-sm">{{ quote.quote }}</p>
    <footer class="blockquote-footer">
        {{ quote.author }}
    </footer>
</blockquote>

logbook/templates/logbook/partials/_squad_scoreboard_member.html
<h3 class="mt-3"> {{ request.user.member.squad.squad_name }}
    Scoreboard</h3>
<div class="row">
    <div class="col-12 scoreboard">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Pos</th>
                <th scope="col">Name</th>
                <th scope="col">Time</th>
                <th scope="col">Split</th>
                <th scope="col">Dist</th>
                <th scope="col">Date</th>
            </tr>
            </thead>
            <tbody>
            {% for erg in erg_tests %}
                {% load auth_extras %}
                {% if request.user.member.is_coach is True or erg.completed_by == request.user.member %}
                    <tr class="user-row">
                        <td> {{ forloop.counter }}</td>
                        <td>{{ user.member }}</td>
                        {% else %}
                    <tr>
                    <td> {{ forloop.counter }}</td>
                    <td>{{ "Teammate" }}</td>
                {% endif %}
            <td>{{ erg.result_time }}</td>
            <td>{{ erg.split_time }}</td>
            <td>{{ erg.distance }}</td>
            <td>{{ erg.completed_at|date:"d M Y" }}</td>
            </tr>
            {% empty %}
                <tr class="no-hover">
                    <td colspan="6" class="text-center"><strong><a
                            href="{% url 'logbook:log-erg' %}">No Ergs
                        submitted
                        for this
                        month. Be the
                        first
                        logging
                        the metrics for this month</a></strong></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>